Authorization
kth-iv1201-group5/recruitment pull request #66
Opened 2022-02-27 15:42 UTC by Hamza-Heidar

- Applicants can't access recruiter pages
- Recruiters can't access applicant pages

**This pull request have completed these problems:**
- Add your completed task here!

2022-02-27 23:58 UTC, arifjehoh requested changes
Fix this, then we can proceed on reviewing.

2022-02-27 23:58 UTC, arifjehoh commented on src/main/java/kth/iv1201/recruitment/config/SecurityConfig.java
> +				.antMatchers("/positions").access("hasRole('ROLE_applicant')")
Remove the empty space.

2022-02-27 23:58 UTC, arifjehoh commented on src/main/java/kth/iv1201/recruitment/controller/WebController.java
> +		return "/positions";
Create `private static final String` variable for position route.

2022-02-27 23:58 UTC, arifjehoh commented on src/main/resources/templates/positions.html
> +</div>
Remove the empty spaces.

2022-02-28 00:00 UTC, arifjehoh commented
@Hamza-Heidar Make sure to remember to use the prefixes in commits.

2022-03-06 12:46 UTC, mrporsev approved these changes

2022-03-06 12:53 UTC, merged